steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/smplverse/metadata', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/smplverse/metadata' ]
images:
- 'gcr.io/smplverse/metadata'
